= Quarkus.io Search

> A Quarkus-powered application that allows full-text search in websites of the Quarkus organization such as https://quarkus.io.

[[development]]
== Development

To launch the application in dev mode:

[source,shell]
----
quarkus dev
# OR
./mvnw quarkus:dev
----

Indexing happens on startup.
Because there is a lot of data to fetch before indexing,
by default dev mode will use a smaller test dataset included in this repository.
To fetch the actual data on startup:

[source,shell]
----
quarkus dev -Dfetching.quarkusio.type=git
# OR
./mvnw quarkus:dev -Dfetching.quarkusio.method=git
----

Or, if you already have a local clone of quarkus.io:

[source,shell]
----
quarkus dev -Dfetching.quarkusio.uri=file:$HOME/my-clone
# OR
./mvnw quarkus:dev -Dfetching.quarkusio.uri=file:$HOME/my-clone
----

Then head over to http://0.0.0.0:9000/q/swagger-ui/ to try the service.

[[deployment]]
== Deployment

Deployment should happen automatically when pushing to the `main` branch.

Maintainers can review the application and update configuration/secrets
at https://console-openshift-console.apps.ospo-osci.z3b1.p1.openshiftapps.com/

Be careful about which configuration you change in the UI,
as deployment may overwrite part of the topology.

[[license]]
== License

This project is licensed under the Apache License Version 2.0.
